apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-prod-dns-clisr
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admins@example.com
    privateKeySecretRef:
      name: le-prod-privkey
    solvers:
    - dns01:
        azureDNS:
          clientID: xxxxxxxxxxxxxxxxxxxxxxxxx
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          subscriptionID: xxxxxxxxxxxxxxxxxxxxxxxxx
          tenantID: xxxxxxxxxxxxxxxxxxxxxxxxx
          resourceGroupName: cbs-dns-rg
          hostedZoneName: dnszone.example.com
          environment: AzurePublicCloud
