# NOT USED
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  annotations:
    # recommended to use namespaced identites https://azure.github.io/aad-pod-identity/docs/configure/match_pods_in_namespace/
    aadpodidentity.k8s.io/Behavior: namespaced 
  name: certmgr-identity
  namespace: cert-manager
spec:
  type: 0 # MSI
  resourceID: /subscriptions/9f922c49-ff04-4442-881d-67aefdf572da/resourcegroups/cbs-dns-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/cbs-autocertk8sdns-id
  clientID: ee419ed6-480c-4eef-a778-cfaa5707e993
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: certmgr-id-binding
  namespace: cert-manager
spec:
  azureIdentity: certmgr-identity
  selector: certmgr-label # This is the label that needs to be set on cert-manager pods
